development:
  adapter: postgresql
  encoding: unicode
  database: hydratr_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hydratr_test
  pool: 5
  host: localhost